import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/footer'
import Navbar from '../components/navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Badger Labs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Navbar />

        <div className="hero section">
          <div className="hero-content">
            <h1 className='hero-heading'>Lorem,<span> ipsum <br /> dolor. </span>Si Amet</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatibus amet non in, quia quam, quas perferendis temporibus quos ex, maiores veritatis ipsam ipsa adipisci nesciunt illum deleniti doloribus? </p>
          </div>

          <div className="hero-banner">
            <div className="aside-content">
              <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ab illum ullam doloribus, hic dolores sapiente, alias fugit, voluptas quas animi repellat ratione sunt similique minima!</p>
            </div>
          </div>
        </div>

        <div className="section features-section">
          <div className="aside-dark">
            <p className='features-heading'>Get the right blah to keep your  business moving forward</p>
            <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Amet adipisci consequatur hic, asperiores facilis cupiditate ipsam provident nihil. Provident culpa corporis minima aspernatur, fugiat nisi. Quidem tempore non et totam.</p>
          </div>
          <div className="aside-light">
            <h1 className='feature-name'><span>Univas</span> Goes Here</h1>
          </div>
        </div>
      </main>

     <Footer />
    </div>
  )
}
